// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUn00ek0244H7QTu97vEeI97ZyH699OU',
    appId: '1:824585926919:web:dda549e8f73bbba4f06da2',
    messagingSenderId: '824585926919',
    projectId: 'hostelmessmanagent',
    authDomain: 'hostelmessmanagent.firebaseapp.com',
    databaseURL: 'https://hostelmessmanagent-default-rtdb.firebaseio.com',
    storageBucket: 'hostelmessmanagent.appspot.com',
    measurementId: 'G-WL1MZD51XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkBZEF9GzYJLjlpL1qfePf55uWQIvC-8',
    appId: '1:824585926919:android:846db2ffc89a75f1f06da2',
    messagingSenderId: '824585926919',
    projectId: 'hostelmessmanagent',
    databaseURL: 'https://hostelmessmanagent-default-rtdb.firebaseio.com',
    storageBucket: 'hostelmessmanagent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgGxsd2WlJj_YZVf0WRyLXyAx_iugka9w',
    appId: '1:824585926919:ios:0c316247c8f3a3e2f06da2',
    messagingSenderId: '824585926919',
    projectId: 'hostelmessmanagent',
    databaseURL: 'https://hostelmessmanagent-default-rtdb.firebaseio.com',
    storageBucket: 'hostelmessmanagent.appspot.com',
    iosBundleId: 'com.example.project02Hackloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgGxsd2WlJj_YZVf0WRyLXyAx_iugka9w',
    appId: '1:824585926919:ios:ecb0cceb0d559b16f06da2',
    messagingSenderId: '824585926919',
    projectId: 'hostelmessmanagent',
    databaseURL: 'https://hostelmessmanagent-default-rtdb.firebaseio.com',
    storageBucket: 'hostelmessmanagent.appspot.com',
    iosBundleId: 'com.example.project02Hackloop.RunnerTests',
  );
}
